---
version: "2.1"
services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server
    hostname: openssh-server #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=password #optional
      - USER_NAME=ubuntu #optional
    volumes:
      - ./2:/config
    ports:
      - 2222:2222
    restart: unless-stopped
  openssh-server2:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server2
    hostname: openssh-server2 #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=password #optional
      - USER_NAME=ubuntu #optional
    volumes:
      - ./1:/config
    ports:
      - 3333:2222
    restart: unless-stopped
