# Default values for nginx-app.1.23.1
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: nginx
  tag: 1.23.1
  pullPolicy: IfNotPresent


service:
  type: NodePort
  port: 80
